const COVERS = [
  {f:"100_daichi_miura_blizzard.jpg",artist:"Daichi",title:"Miura Blizzard"},
  {f:"103_kairikibear_ruma.jpg",artist:"Kairikibear",title:"Ruma"},
  {f:"104_kairikibear_darling_dance.jpg",artist:"Kairikibear",title:"Darling Dance"},
  {f:"106_eve_last_dance.jpg",artist:"Eve",title:"Last Dance"},
  {f:"107_eve_kaikai_kitan.jpg",artist:"Eve",title:"Kaikai Kitan"},
  {f:"10_official_hige_dandism_cry_baby.jpg",artist:"Official",title:"Hige Dandism Cry Baby"},
  {f:"115_sawano_hiroyuki_perfect_time.jpg",artist:"Sawano",title:"Hiroyuki Perfect Time"},
  {f:"116_aimer_last_stardust.jpg",artist:"Aimer",title:"Last Stardust"},
  {f:"117_aimer_brave_shine.jpg",artist:"Aimer",title:"Brave Shine"},
  {f:"126_deco_27_the_vampire.jpg",artist:"Deco",title:"27 The Vampire"},
  {f:"133_yui_again.jpg",artist:"Yui",title:"Again"},
  {f:"135_oxt_highest.jpg",artist:"Oxt",title:"Highest"},
  {f:"136_oxt_go_cry_go.jpg",artist:"Oxt",title:"Go Cry Go"},
  {f:"137_oxt_hollow_hunger.jpg",artist:"Oxt",title:"Hollow Hunger"},
  {f:"139_gen_hoshino_koi.jpg",artist:"Gen",title:"Hoshino Koi"},
  {f:"13_akasaki_bunny_girl.jpg",artist:"Akasaki",title:"Bunny Girl"},
  {f:"140_kenshi_yonezu_lady.jpg",artist:"Kenshi",title:"Yonezu Lady"},
  {f:"142_kenshi_yonezu_lemon.jpg",artist:"Kenshi",title:"Yonezu Lemon"},
  {f:"143_kenshi_yonezu_kick_back.jpg",artist:"Kenshi",title:"Yonezu Kick Back"},
  {f:"146_zutomayo_taidada.jpg",artist:"Zutomayo",title:"Taidada"},
  {f:"147_yama_haru_wo_tsugeru.jpg",artist:"Yama",title:"Haru Wo Tsugeru"},
  {f:"148_aimyon_marigold.jpg",artist:"Aimyon",title:"Marigold"},
  {f:"14_natori_overdose.jpg",artist:"Natori",title:"Overdose"},
  {f:"152_imase_night_dancer.jpg",artist:"Imase",title:"Night Dancer"},
  {f:"153_king_gnu_specialz.jpg",artist:"King",title:"Gnu Specialz"},
  {f:"154_iyowa_kyu_kurarin.jpg",artist:"Iyowa",title:"Kyu Kurarin"},
  {f:"172_yoshida_yasei_override.jpg",artist:"Yoshida",title:"Yasei Override"},
  {f:"173_leina_utatane.jpg",artist:"Leina",title:"Utatane"},
  {f:"177_yoasobi_undead.jpg",artist:"Yoasobi",title:"Undead"},
  {f:"179_leina_kuwazugirai.jpg",artist:"Leina",title:"Kuwazugirai"},
  {f:"193_frederic_oddloop.jpg",artist:"Frederic",title:"Oddloop"},
  {f:"195_deco_27_dscf.jpg",artist:"Deco",title:"27 Dscf"},
  {f:"206_vaundy_tokyo_flash.jpg",artist:"Vaundy",title:"Tokyo Flash"},
  {f:"211_dannie_may_ejanaika.jpg",artist:"Dannie",title:"May Ejanaika"},
  {f:"213_tomoo_ginger.jpg",artist:"Tomoo",title:"Ginger"},
  {f:"214_sarm_bonbon_girl.jpg",artist:"Sarm",title:"Bonbon Girl"},
  {f:"219_yasuharu_takanashi_fairy_tail_main_theme.jpg",artist:"Yasuharu",title:"Takanashi Fairy Tail Main Theme"},
  {f:"224_sakanaction_kaiju.jpg",artist:"Sakanaction",title:"Kaiju"},
  {f:"228_hoshimachi_suisei_caramel_pain.jpg",artist:"Hoshimachi",title:"Suisei Caramel Pain"},
  {f:"229_hoshimachi_suisei_orbital_period.jpg",artist:"Hoshimachi",title:"Suisei Orbital Period"},
  {f:"232_ro2noki_hymn_to_the_decadent_life.jpg",artist:"Ro2noki",title:"Hymn To The Decadent Life"},
  {f:"234_linked_horizon_guren_no_yumiya.jpg",artist:"Linked",title:"Horizon Guren No Yumiya"},
  {f:"237_linked_horizon_akatsuki_no_requiem.jpg",artist:"Linked",title:"Horizon Akatsuki No Requiem"},
  {f:"238_ai_higuchi_akuma_no_ko.jpg",artist:"Ai",title:"Higuchi Akuma No Ko"},
  {f:"240_ali_wild_side.jpg",artist:"Ali",title:"Wild Side"},
  {f:"244_sekai_no_owari_habit.jpg",artist:"Sekai",title:"No Owari Habit"},
  {f:"249_hump_back_haikei_shounenyo.jpg",artist:"Hump",title:"Back Haikei Shounenyo"},
  {f:"252_vk_blanka_black_rover.jpg",artist:"Vk",title:"Blanka Black Rover"},
  {f:"253_yu_peng_chen_genshin_impact_main_theme.jpg",artist:"Yu",title:"Peng Chen Genshin Impact Main Theme"},
  {f:"256_shinsei_kamattechan_boku_no_sensou.jpg",artist:"Shinsei",title:"Kamattechan Boku No Sensou"},
  {f:"257_official_hige_dandism_pretender.jpg",artist:"Official",title:"Hige Dandism Pretender"},
  {f:"265_citypopvibes_sweet_delusion.jpg",artist:"Citypopvibes",title:"Sweet Delusion"},
  {f:"276_aimer_ninelie.jpg",artist:"Aimer",title:"Ninelie"},
  {f:"280_zutomayo_cream.jpg",artist:"Zutomayo",title:"Cream"},
  {f:"281_gesu_no_kiwami_otome_crying_march.jpg",artist:"Gesu",title:"No Kiwami Otome Crying March"},
  {f:"289_people_1_dogland.jpg",artist:"People",title:"1 Dogland"},
  {f:"294_eill_koko_de_iki_wo_shite.jpg",artist:"Eill",title:"Koko De Iki Wo Shite"},
  {f:"304_spectrum_f_l_y.jpg",artist:"Spectrum",title:"F L Y"},
  {f:"320_pompadolls_gluttony.jpg",artist:"Pompadolls",title:"Gluttony"},
  {f:"321_pompadolls_spotlight_junkie.jpg",artist:"Pompadolls",title:"Spotlight Junkie"},
  {f:"324_hideki_taniuchi_l_no_theme.jpg",artist:"Hideki",title:"Taniuchi L No Theme"},
  {f:"329_leina_medicine.jpg",artist:"Leina",title:"Medicine"},
  {f:"332_kaoru_wada_futari_no_kimochi.jpg",artist:"Kaoru",title:"Wada Futari No Kimochi"},
  {f:"334_yiruma_river_flows_in_you.jpg",artist:"Yiruma",title:"River Flows In You"},
  {f:"33_9lana_balalaika.jpg",artist:"9lana",title:"Balalaika"},
  {f:"341_nyarons_highway_summer.jpg",artist:"Nyarons",title:"Highway Summer"},
  {f:"343_shinra_bansho_toge.jpg",artist:"Shinra",title:"Bansho Toge"},
  {f:"350_bocchi_kimi_wa_natsukaze.jpg",artist:"Bocchi",title:"Kimi Wa Natsukaze"},
  {f:"356_issey_nightmare_restaurant.jpg",artist:"Issey",title:"Nightmare Restaurant"},
  {f:"35_cinnamons_summertime.jpg",artist:"Cinnamons",title:"Summertime"},
  {f:"361_stereopony_stand_by_me.jpg",artist:"Stereopony",title:"Stand By Me"},
  {f:"364_choqmay_hey_calling.jpg",artist:"Choqmay",title:"Hey Calling"},
  {f:"370_bradio_flyers.jpg",artist:"Bradio",title:"Flyers"},
  {f:"373_hoshimachi_suisei_stellar_stellar.jpg",artist:"Hoshimachi",title:"Suisei Stellar Stellar"},
  {f:"379_dazbee_bitter_loss.jpg",artist:"Dazbee",title:"Bitter Loss"},
  {f:"380_dazbee_sympathy.jpg",artist:"Dazbee",title:"Sympathy"},
  {f:"381_dazbee_nemuranai_yume.jpg",artist:"Dazbee",title:"Nemuranai Yume"},
  {f:"382_dazbee_dream_island.jpg",artist:"Dazbee",title:"Dream Island"},
  {f:"383_dazbee_lovestruck.jpg",artist:"Dazbee",title:"Lovestruck"},
  {f:"385_dazbee_scarlet.jpg",artist:"Dazbee",title:"Scarlet"},
  {f:"386_dazbee_catch_you_catch_me.jpg",artist:"Dazbee",title:"Catch You Catch Me"},
  {f:"388_dazbee_angel_s_fake.jpg",artist:"Dazbee",title:"Angel S Fake"},
  {f:"389_raon_eclipse.jpg",artist:"Raon",title:"Eclipse"},
  {f:"38_lisa_crossing_field.jpg",artist:"Lisa",title:"Crossing Field"},
  {f:"391_dazbee_time_after_time.jpg",artist:"Dazbee",title:"Time After Time"},
  {f:"393_dazbee_bambi.jpg",artist:"Dazbee",title:"Bambi"},
  {f:"411_eve_ghost_avenue.jpg",artist:"Eve",title:"Ghost Avenue"},
  {f:"418_kenshi_yonezu_iris_out.jpg",artist:"Kenshi",title:"Yonezu Iris Out"},
  {f:"420_bradio_fanfare.jpg",artist:"Bradio",title:"Fanfare"},
  {f:"421_kenshi_yonezu_jane_doe.jpg",artist:"Kenshi",title:"Yonezu Jane Doe"},
  {f:"422_nonoc_memento.jpg",artist:"Nonoc",title:"Memento"},
  {f:"424_sekai_no_owari_rpg.jpg",artist:"Sekai",title:"No Owari Rpg"},
  {f:"426_ado_cat_s_eye.jpg",artist:"Ado",title:"Cat S Eye"},
  {f:"427_caramel_candid_caramel_girls.jpg",artist:"Caramel",title:"Candid Caramel Girls"},
  {f:"430_penthouse_undertaker.jpg",artist:"Penthouse",title:"Undertaker"},
  {f:"431_official_hige_dandism_shukumei.jpg",artist:"Official",title:"Hige Dandism Shukumei"},
  {f:"432_official_hige_dandism_rashisa.jpg",artist:"Official",title:"Hige Dandism Rashisa"},
  {f:"438_ado_magic.jpg",artist:"Ado",title:"Magic"},
  {f:"43_konomi_suzuki_this_game.jpg",artist:"Konomi",title:"Suzuki This Game"},
  {f:"442_eill_action.jpg",artist:"Eill",title:"Action"},
  {f:"446_yuki_hayashi_you_say_run.jpg",artist:"Yuki",title:"Hayashi You Say Run"},
  {f:"447_yuki_hayashi_jet_set_run.jpg",artist:"Yuki",title:"Hayashi Jet Set Run"},
  {f:"44_oxt_clattanoia.jpg",artist:"Oxt",title:"Clattanoia"},
  {f:"453_andora_flicker.jpg",artist:"Andora",title:"Flicker"},
  {f:"457_zutomayo_yushinron.jpg",artist:"Zutomayo",title:"Yushinron"},
  {f:"459_tomioka_ai_good_bye_bye.jpg",artist:"Tomioka",title:"Ai Good Bye Bye"},
  {f:"468_hitorioto_utakatanokoi.jpg",artist:"Hitorioto",title:"Utakatanokoi"},
  {f:"46_oxt_silent_solitude.jpg",artist:"Oxt",title:"Silent Solitude"},
  {f:"471_vuat_monsters_and_heroes.jpg",artist:"Vuat",title:"Monsters And Heroes"},
  {f:"472_tsukuyomi_moonlight_at_midday.jpg",artist:"Tsukuyomi",title:"Moonlight At Midday"},
  {f:"474_703goushitsu_aoboshi.jpg",artist:"703goushitsu",title:"Aoboshi"},
  {f:"475_luciela_meitetsukou.jpg",artist:"Luciela",title:"Meitetsukou"},
  {f:"479_natori_in_my_head.jpg",artist:"Natori",title:"In My Head"},
  {f:"47_fripside_only_my_railgun.jpg",artist:"Fripside",title:"Only My Railgun"},
  {f:"483_nora_sessesse_no_yoiyoiyoi.jpg",artist:"Nora",title:"Sessesse No Yoiyoiyoi"},
  {f:"485_kroi_method.jpg",artist:"Kroi",title:"Method"},
  {f:"486_lavt_l4dy.jpg",artist:"Lavt",title:"L4dy"},
  {f:"489_ado_and_rib_matoryoshka.jpg",artist:"Ado",title:"And Rib Matoryoshka"},
  {f:"48_true_sincerely.jpg",artist:"True",title:"Sincerely"},
  {f:"491_mori_calliope_let_s_just_crash.jpg",artist:"Mori",title:"Calliope Let S Just Crash"},
];
